# Кастомный размер чара, используйте для текстур itemsadder
custom-chars-width:
  '^': 10
# Символ, который будет использоваться для пробелов
space-symbol: '.'
# Длина space-symbol в пикселях
space-symbol-width: 2
# Кастомные текстуры для мест топа
custom-place-chars:
  1: '&61'
  2: '&e2'
# Начальное максимальное значение в пикселях для строки лидерборда
# При необходимости будет автоматически увеличиваться
start-max-width: 160
# Минимальная длинна пробела в пикселях
min-space-width: 10
# Шаг расширения лидерборда при превышение максимальной длинны
space-extension-step: 5
formats:
  # Плейсхолдер топа - формат энтри
  # Локальные плейсхолдеры:
  # {0} место (учитывает параметры custom-place-chars)
  # {1} имя игрока
  # {2} префикс игрока
  # {3} значение топа
  # {4} отформатированный пробел из space-symbol
  # {5} кол-во пикселей для выравнивания (Можете использовать %img_offset_{5}% для прозрачных отступов с itemsadder)
  vault_eco_balance_fixed: '{0} | {2} {1} {4} &a{3}$'